# push-adr226.ps1 -- generated by tools/deliver.py from tools/delivery/adr226.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr226.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr226.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr226 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR226 pushed."; exit 0 }
  Write-Host "adr226 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr225.ps1"), (Join-Path $root "push-adr225.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-225-a-build-that-included-thirteen-and-a-ci-that-fetched-eleven-2026-09-17.md
  if ($st) { Write-Host "adr225 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-226-the-script-that-was-refused-before-its-first-line-2026-09-17.md `
  docs/CHANGELOG-2026-09-17-adr226-the-script-that-was-refused-before-its-first-line.md `
  tools/deliver.py `
  tools/verify/verify_delivery.py `
  tools/mutate_delivery.py `
  tools/push/push-adr225-siblings.ps1 `
  tools/verify/verify_board.py `
  tools/harness_board.py `
  tools/delivery/adr226.json `
  docs/AI_HARNESS.md `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/push/push-adr226.ps1
git -C $csrbt commit -m "ADR-226: push-adr225-siblings.ps1 was refused by PowerShell before its first line ran, and nothing in the kit had ever parsed a push script" `
  -m "Write-Host with a dollar-dir-colon inside a string is a drive-qualified variable to PowerShell and a parse error; the whole file is refused before its first line executes. The main script had printed ADR225 pushed; the sibling one pushed nothing, so WholeHog's workflow and SmokeHouse's fix stayed on the operator's disk. --check compares every generated script to its manifest and the sibling script is hand-written, which is exactly the one nothing else holds. deliver.ps_parse_faults returns every such variable that is not one of the nine qualifiers PowerShell knows, with its line, and --check reads every script under tools/push, generated or not, naming the file, the line and the fix. Both lines are braced now. verify_delivery 76 to 82, mutate_delivery 60 to 63, all killed. Held: a real PowerShell parse; price, a pwsh where --check runs; trigger, the second class of parse fault a script ships with. And delivering it found a second thing: verify_board run on the operator's VM failed its byte-for-byte check with identical ledgers, because the board stamped readings in local time; stamps are UTC now, the footer says so, and verify_board holds the same ledgers to the same bytes under three zones, 118 to 121." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR226: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr226.json)) { Write-Error "ADR226: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR226: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr225.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR226 pushed."
