# push-adr243.ps1 -- generated by tools/deliver.py from tools/delivery/adr243.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr243.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr243.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr243 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR243 pushed."; exit 0 }
  Write-Host "adr243 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr242.ps1"), (Join-Path $root "push-adr242.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-242-a-voucher-says-nothing-it-was-not-told-2026-09-23.md
  if ($st) { Write-Host "adr242 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-243-a-model-keeps-the-numbers-it-was-given-2026-09-23.md `
  docs/CHANGELOG-2026-09-23-adr243-a-model-keeps-the-numbers-it-was-given.md `
  docs/AI_HARNESS.md `
  docs/ecology-lab.html `
  tools/tasks/page-ecology-lab-science.json `
  tools/task_ledger.json `
  tools/verify/verify_eco.py `
  tools/mutate_ecolab.py `
  tools/harness_board.py `
  tools/delivery/adr243.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/address_ledger.json `
  tools/push/push-adr243.ps1
git -C $csrbt commit -m "ADR-243: a model keeps the numbers it was given -- the ecology lab's theory bench keeps what each model was typed and says whose numbers it is drawn from, and the two-site verdict says which figure it is reading" `
  -m "The tenth blind trial filed two defects on the ecology lab. Choosing a theory model rebuilt its parameter boxes from the defaults, so the numbers a model had been given were gone after a look at another model and the .eco line built next was a protocol nobody typed; now each model keeps what it was given, puts it back when chosen again, and the line under the boxes says which numbers it is drawn from. The two-site verdict read Bray-Curtis alone and called sites sharing 3 of 7 kinds nearly identical; now, where the counts agree and the membership does not, it names both figures and places the turnover among the scarce kinds, and identical sites are called identical. Task 345 to 359, refuted on the old page; verify_eco 200 to 227 against a port of the word and the model; new mutate_ecolab runner, 12 killed." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR243: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr243.json)) { Write-Error "ADR243: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR243: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr242.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR243 pushed."
