# push-adr188.ps1 -- generated by tools/deliver.py from tools/delivery/adr188.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr188.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr188.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr188 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR188 pushed."; exit 0 }
  Write-Host "adr188 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr187.ps1"), (Join-Path $root "push-adr187.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- tools/traces/blind3/PROVENANCE.md
  if ($st) { Write-Host "adr187 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  tools/harness_plugin_page.py `
  tools/verify/verify_report.py `
  tools/mutate_report.py `
  tools/mutant_ledger.json `
  tools/outputs_ledger.json `
  tools/badinput_ledger.json `
  tools/entry_ledger.json `
  tools/readable_ledger.json `
  tools/delivery_ledger.json `
  tools/verify/counts.json `
  tools/harness_board.html `
  tools/published.json `
  tools/delivery/adr188.json `
  docs/ADR-188-names-at-the-door-2026-09-11.md `
  docs/CHANGELOG-2026-09-11-adr188-names-at-the-door.md `
  docs/AI_HARNESS.md `
  tools/push/push-adr188.ps1
git -C $csrbt commit -m "ADR-188: names at the door -- every selector argument takes a control ADDRESS (#id, @name, or an index stamped with its snapshot), and every control publishes the shortest one that resolves back to it" `
  -m "THE COMPLAINT ALL FOUR BLIND OPERATORS MADE. action_btn:N indexes the whole page and renumbers on every structural change; the snapshot publishes a stable id; no tool accepted one, because @control:<name> was resolved by the TASK RUNNER, on the far side of the door the operator speaks through. Every selector argument now takes an address: the index as before, the index stamped with the snapshot it came from (kind:index@v<digest>), the page's own id (#cName), or the page's own name (@working name, @rCov/4, @iList/died#2, @kind=drop_zone) -- ADR-128's grammar unchanged, and '@control:' accepted verbatim. Every control publishes the shortest address that resolves back to itself through the resolver itself; on the four trial pages every control has one and no index is left. observe carries a version digest of the numbering; a stamped index whose version moved is refused and told what is at that index now instead of pressing it. risk_for resolves first -- otherwise every stable address would have read as 'resolves to nothing' and been raised to DESTRUCTIVE -- and does not raise a name that names nothing, while an unresolvable positional selector still is (ADR-141) and a destructive control still is through either spelling. The runner keeps its own find_control and the two are held to each other on every name of three real pages. verify_report 120 -> 136, mutate_report 75 -> 89. No page and no task was edited; the walk drives the same 25,392 commands." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_01YPcb1A7CejriRgL9xLrhJ3"
git -C $csrbt push
$t = Join-Path $root "_to_delete\adr128.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr129.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr130.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr131.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr132.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr133.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr134.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr135.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr136.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr137.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr138.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr139.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr140.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr141.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr142.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr143.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr144.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr145.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr146.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr147.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr148.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr149.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr150.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr151.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr152.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr153.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr154.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr155.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr156.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr157.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr158.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr159.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr160.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr161.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr162.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr163.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr164.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr165.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr166.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr167.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr168.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr169.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr170.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr171.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr172.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr173.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr174.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr175.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr176.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr177.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr178.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr179.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr180.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr181.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr182.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr183.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr184.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr185.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr186.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr187.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR188 pushed."
