# push-adr242.ps1 -- generated by tools/deliver.py from tools/delivery/adr242.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr242.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr242.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr242 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR242 pushed."; exit 0 }
  Write-Host "adr242 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr241.ps1"), (Join-Path $root "push-adr241.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-241-the-count-says-which-tree-it-counted-2026-09-22.md
  if ($st) { Write-Host "adr241 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-242-a-voucher-says-nothing-it-was-not-told-2026-09-23.md `
  docs/CHANGELOG-2026-09-23-adr242-a-voucher-says-nothing-it-was-not-told.md `
  docs/AI_HARNESS.md `
  docs/releve.html `
  docs/soil-suite.html `
  tools/tasks/page-releve-science.json `
  tools/task_ledger.json `
  tools/verify/verify_rv.py `
  tools/mutate_rv.py `
  tools/harness_board.py `
  tools/delivery/adr242.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/address_ledger.json `
  tools/push/push-adr242.ps1
git -C $csrbt commit -m "ADR-242: a voucher says nothing it was not told -- the relevé's voucher dials start unset, a voucher is refused until its material is said, an unset phenophase is recorded as none, and the sheet says what the next voucher will carry" `
  -m "The seventh blind trial recorded a relevé voucher without touching material or phenophase and its herbarium label carried '[in flower, flowering]', a statement the collector never made. Both dials now start unset; Record voucher is refused until the material is said; a voucher with no phenophase records none and its label, list row, export line and confirmation say so; and vouNote says what the next voucher will be recorded as, since the dials carry forward. The occurrence dial keeps its vegetative default, which is the common case. Task 183 to 187 confirmed and refuted on the old page; verify_rv 81 to 94 against the record KEEP holds; new mutate_rv runner." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR242: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr242.json)) { Write-Error "ADR242: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR242: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr241.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR242 pushed."
