# push-adr237.ps1 -- generated by tools/deliver.py from tools/delivery/adr237.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr237.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr237.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr237 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR237 pushed."; exit 0 }
  Write-Host "adr237 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr236.ps1"), (Join-Path $root "push-adr236.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-236-a-figure-the-clock-carries-is-not-carried-2026-09-22.md
  if ($st) { Write-Host "adr236 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-237-a-perfect-fit-is-not-an-unstable-one-2026-09-22.md `
  docs/CHANGELOG-2026-09-22-adr237-a-perfect-fit-is-not-an-unstable-one.md `
  docs/AI_HARNESS.md `
  docs/ordination.html `
  tools/ord.py `
  tools/tasks/page-ordination-science.json `
  tools/task_ledger.json `
  tools/verify/verify_ord.py `
  tools/mutate_ord.py `
  tools/harness_board.py `
  tools/delivery/adr237.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr237.ps1
git -C $csrbt commit -m "ADR-237: a perfect fit is not an unstable one -- the ordination page stops calling stress 0.000 unstable, counts its unreadable values in agreement, and clears a toast that has gone" `
  -m "The eighth blind trial filed three ordination defects and all three were live. At stress 0.000 on four and five sites the starts box said the solution was not stable because 1 of 12 starts agreed; at stress zero every start that reached it is an exact fit and with few sites there are many, so it now says how many reached a perfect fit and that the picture is one of several exact ones, and the copied coordinates say so too. One unreadable value was taken as zero, not were. A toast that has slid away is cleared, so the demo's message is not still read after your own data. Found: the page seeds its starts from the clock, so the task holds the sentence and the suite holds the counts' consistency. Task 89 to 100 confirmed, verify_ord 114 to 129 with an independent second stress-0 arrangement, new mutate_ord 8 of 8." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR237: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr237.json)) { Write-Error "ADR237: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR237: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr236.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR237 pushed."
