# push-adr234.ps1 -- generated by tools/deliver.py from tools/delivery/adr234.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr234.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr234.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr234 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR234 pushed."; exit 0 }
  Write-Host "adr234 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr233.ps1"), (Join-Path $root "push-adr233.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-233-the-report-says-what-the-numbers-say-2026-09-21.md
  if ($st) { Write-Host "adr233 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-234-a-goals-figures-are-bound-2026-09-21.md `
  docs/CHANGELOG-2026-09-21-adr234-a-goals-figures-are-bound.md `
  docs/AI_HARNESS.md `
  docs/tree-proofs.html `
  tools/harness_tasks.py `
  tools/tasks/page-tree-proofs-science.json `
  tools/tasks/page-tree-visualizer-science.json `
  tools/tasks/page-ecology-lab-science.json `
  tools/task_ledger.json `
  tools/verify/verify_brief.py `
  tools/verify/verify_proofs.py `
  tools/verify/verify_tv.py `
  tools/mutate_brief.py `
  tools/mutate_proofs.py `
  tools/harness_board.py `
  tools/delivery/adr234.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr234.ps1
git -C $csrbt commit -m "ADR-234: a goal's figures are bound to the claims that hold them -- the tree visualizer's 24 nodes, the tree proofs' 6 rotations and its ascending note, and a task that cannot load when its prose and its claim disagree" `
  -m "Three blind trials caught goal prose stating figures the page never shows while the task held the right ones. A task may now declare figures: a phrase of the goal, a required step and a claim; load_task refuses the task unless the claim's value is in the phrase as a whole token. 18 bound on the tree proofs, tree visualizer and ecology lab, each goal corrected first. The tree proofs' worst-case note said ascending over a loop counting down; it is now read off the tree and the task holds the exact sentence. verify_brief 31 to 46, verify_proofs 143 to 149 against an independent splay port, verify_tv 115 to 118 against a mulberry32 port; mutate_brief 14 to 24 (two stale anchors fixed) and new mutate_proofs 8 of 8, all killed." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR234: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr234.json)) { Write-Error "ADR234: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR234: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr233.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR234 pushed."
