# push-adr235.ps1 -- generated by tools/deliver.py from tools/delivery/adr235.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr235.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr235.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr235 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR235 pushed."; exit 0 }
  Write-Host "adr235 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr234.ps1"), (Join-Path $root "push-adr234.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-234-a-goals-figures-are-bound-2026-09-21.md
  if ($st) { Write-Host "adr234 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-235-the-ledger-is-about-the-code-as-it-is-2026-09-21.md `
  docs/CHANGELOG-2026-09-21-adr235-the-ledger-is-about-the-code-as-it-is.md `
  docs/AI_HARNESS.md `
  tools/audit_anchors.py `
  tools/verify/verify_anchors.py `
  tools/mutate_anchors.py `
  tools/mutate_entry.py `
  tools/harness_board.py `
  tools/delivery/adr235.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr235.ps1
git -C $csrbt commit -m "ADR-235: the mutant ledger is about the code as it is -- a static audit of every runner's anchors and catalogue, and mutate_entry's thirteen days of kills against a catalogue it no longer had" `
  -m "The board's mutant gate reads a ledger each runner writes when it runs, and nothing rereads the runner in between: ADR-234 found two mutate_brief anchors that no longer landed while the ledger said 14 of 14. tools/audit_anchors.py reads every runner's catalogue without running it and reports stale anchors (found nowhere in the code a runner could break, the sibling engine included) and drifted runners (catalogue not the one the ledger recorded). verify_anchors, 23 checks, holds it on a scratch kit and gates the real one: 33 runners, 1,185 mutants, none stale, none drifted. mutate_anchors, 12 of 12 killed. Found: mutate_entry had drifted since ADR-170; re-run it read one inconclusive, now fixed and 17 of 17." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR235: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr235.json)) { Write-Error "ADR235: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR235: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr234.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR235 pushed."
