# push-adr180.ps1 -- generated by tools/deliver.py from tools/delivery/adr180.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr180.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr179.ps1"), (Join-Path $root "push-adr179.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- tools/verify/verify_epr.py
  if ($st) { Write-Host "adr179 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  tools/audit_readable.py `
  tools/harness_plugin_page.py `
  tools/verify/verify_readable.py `
  tools/mutate_readable.py `
  tools/verify/verify_report.py `
  tools/mutate_report.py `
  tools/verify/verify_sd.py `
  tools/tasks/page-survey-design-science.json `
  tools/mutant_ledger.json `
  tools/outputs_ledger.json `
  tools/badinput_ledger.json `
  tools/entry_ledger.json `
  tools/readable_ledger.json `
  tools/task_ledger.json `
  tools/delivery_ledger.json `
  tools/verify/counts.json `
  tools/harness_board.html `
  tools/published.json `
  tools/delivery/adr180.json `
  docs/ADR-180-the-figures-beside-the-controls-2026-09-10.md `
  docs/CHANGELOG-2026-09-10-adr180-the-figures-beside-the-controls.md `
  docs/AI_HARNESS.md `
  tools/push/push-adr180.ps1
git -C $csrbt commit -m "ADR-180: the figures beside the controls -- the readable audit reads an entry host by what remains once its widgets are removed; 42 more elements measured, the survey's event tree a box held byte for byte, every ceiling 0" `
  -m "ADR-146'S HOLE, CLOSED. The readable audit skipped any element holding a control, whole -- so a figure written beside a button (the pheno tracker's ranked run, the scout's per-stop counts and rotation verdicts, the notebook's quadrat counts, the survey's event tree with a copy button per row) was never measured; ADR-171 named it and carried it. The audit now reads such a host by what remains once its controls (data-h, button, input, select, textarea, label, a[href]) and the kit's widget wrappers (.fek-*) are subtracted from a clone, the same subtraction on the baseline: a kit label is not a figure, a count beside a button is, static prose with a link is not written. Written 270 -> 312, six blind. The survey's event tree becomes a box (read-report names tree by its whole id; verify_report 115, mutate_report 69/69, anchor widened); the survey task holds boxes.tree byte for byte, fifteen rows SGH2026:survey:01 to visit:08 (73 -> 74), pinned by verify_sd's port of the example's ID scheme (70 -> 73). Five declared furniture with reasons (pRg, fkq, scorePanel, traitChips, wEditor). Every ceiling 0. verify_readable 37, mutate_readable 33/33 + 1 recorded equivalent. No page was edited." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_01YPcb1A7CejriRgL9xLrhJ3"
git -C $csrbt push
$t = Join-Path $root "_to_delete\adr128.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr129.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr130.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr131.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr132.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr133.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr134.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr135.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr136.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr137.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr138.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr139.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr140.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr141.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr142.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr143.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr144.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr145.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr146.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr147.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr148.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr149.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr150.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr151.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr152.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr153.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr154.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr155.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr156.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr157.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr158.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr159.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr160.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr161.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr162.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr163.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr164.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr165.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr166.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr167.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr168.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr169.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr170.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr171.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr172.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr173.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr174.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr175.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr176.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr177.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr178.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr179.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR180 pushed."
