# push-adr227.ps1 -- generated by tools/deliver.py from tools/delivery/adr227.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr227.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr227.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr227 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR227 pushed."; exit 0 }
  Write-Host "adr227 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr226.ps1"), (Join-Path $root "push-adr226.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-226-the-script-that-was-refused-before-its-first-line-2026-09-17.md
  if ($st) { Write-Host "adr226 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-227-the-page-that-graded-everything-and-was-graded-by-nothing-2026-09-17.md `
  docs/CHANGELOG-2026-09-17-adr227-the-page-that-graded-everything-and-was-graded-by-nothing.md `
  tools/mutate_board.py `
  tools/harness_board.py `
  tools/verify/verify_board.py `
  tools/delivery/adr227.json `
  docs/AI_HARNESS.md `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr227.ps1
git -C $csrbt commit -m "ADR-227: the board graded everything and was graded by nothing -- a mutant runner for the renderer, and a fixture ledger set with every gate broken" `
  -m "harness_board.py was the one subject in the kit with no mutant runner, and verify_board held it against ledgers that are green, so a renderer that summed of for n or rendered every engine good produced the same page and passed every check; measured on a copy, 121 of 121 with survived forced to zero. The obvious runner would have lied: every mutant that moves a byte dies at the byte-for-byte check and proves only that a byte moved. verify_board section 9 holds a fixture ledger set with every gate broken at known numbers, summary to 39 exact figures and render to the bytes of each row, 121 to 204. tools/mutate_board.py, 43 mutants, each re-rendering its own board before the suite runs so only a rule can kill it; a prose-only mutant survives it, which is the proof. 43 of 43 on the first honest run; the renderer had nothing wrong in it. Held: a second fixture with every gate met and a reading below its ceiling; trigger, the first mutant this runner misses." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR227: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr227.json)) { Write-Error "ADR227: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR227: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr226.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR227 pushed."
