# push-adr236.ps1 -- generated by tools/deliver.py from tools/delivery/adr236.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr236.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr236.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr236 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR236 pushed."; exit 0 }
  Write-Host "adr236 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr235.ps1"), (Join-Path $root "push-adr235.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-235-the-ledger-is-about-the-code-as-it-is-2026-09-21.md
  if ($st) { Write-Host "adr235 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-236-a-figure-the-clock-carries-is-not-carried-2026-09-22.md `
  docs/CHANGELOG-2026-09-22-adr236-a-figure-the-clock-carries-is-not-carried.md `
  docs/AI_HARNESS.md `
  tools/audit_carried.py `
  tools/verify/verify_carried.py `
  tools/mutate_carried.py `
  tools/delivery/adr236.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/carried_ledger.json `
  tools/badinput_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr236.ps1
git -C $csrbt commit -m "ADR-236: a figure the clock carries is not carried -- audit_carried reads every page under two clocks, and a figure counts as carried only if both carry it" `
  -m "audit_carried matches each figure a page works out against every number in its exports, and exports carry their time: ADR-234's run read the releve's 49 taxa in pack as carried by a timestamp's 49 and flipped its declaration idle. Every page is now read twice, on the real clock and on one shifted by 405 days 7 h 23 m 31 s, so no field of a timestamp is the same under both; a figure is carried only if both readings carry it. The clock is shifted, not frozen, so durations still tick. verify_carried 47 to 55 with a fixture whose figure only its export's timestamp carries; mutate_carried 29 to 36. The kit reads exactly what it read before: 317 figures, none lost." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR236: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr236.json)) { Write-Error "ADR236: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR236: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr235.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR236 pushed."
