# push-adr229.ps1 -- generated by tools/deliver.py from tools/delivery/adr229.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr229.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr229.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr229 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR229 pushed."; exit 0 }
  Write-Host "adr229 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr228.ps1"), (Join-Path $root "push-adr228.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-228-the-two-fields-an-operator-could-not-send-2026-09-18.md
  if ($st) { Write-Host "adr228 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-229-a-stamp-says-which-series-it-is-2026-09-18.md `
  docs/CHANGELOG-2026-09-18-adr229-a-stamp-says-which-series-it-is.md `
  docs/AUTOMATION-HARNESS.md `
  tools/harness_contract.py `
  tools/harness_plugin_page.py `
  tools/harness_mcp.py `
  tools/verify/verify_contract.py `
  tools/verify/verify_report.py `
  tools/verify/verify_walk.py `
  tools/verify/verify_tasks.py `
  tools/mutate_contract.py `
  tools/mutate_report.py `
  tools/traces/blind7/PROVENANCE.md `
  tools/traces/blind7/page-food-web-science.jsonl.gz `
  tools/traces/blind7/page-releve-science.jsonl.gz `
  tools/traces/blind7/page-tree-proofs-science.jsonl.gz `
  tools/traces/blind7/page-ethogram-science.jsonl.gz `
  tools/traces/blind7/tasks/page-food-web-science.json `
  tools/traces/blind7/tasks/page-releve-science.json `
  tools/traces/blind7/tasks/page-tree-proofs-science.json `
  tools/traces/blind7/tasks/page-ethogram-science.json `
  tools/delivery/adr229.json `
  docs/AI_HARNESS.md `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr229.ps1
git -C $csrbt commit -m "ADR-229: a stamp says which series it is (protocol 1.9) -- and the seventh blind trial, four more pages nobody had driven, measures that nobody is told a page moved when it had not" `
  -m "The snapshot's stamp and the report's were both s plus twelve hex and nothing said which was which; all four sixth-trial operators handed the report's to if_stamp and were refused stale, told the page had moved, about a page that had not. A report stamp is r plus twelve hex now; if_stamp handed one is refused invalid_argument before any look, naming both kinds and the fix; observe and read-report handed the other kind answer the whole document and name the kind; the manifest publishes a stamps block. verify_contract 221 to 230, verify_report 248 to 249, mutate_contract 105 to 111, mutate_report 149 to 151. The seventh blind trial -- food web, releve, tree proofs, ethogram, one attempt each, 42 of 69 outcomes and 322 of 370 claims in 216 calls -- shows every wrong-kind if_stamp refused as the wrong kind and corrected on the next move, and zero report stamps answered stale; verify_tasks 411 to 429 holds both numbers. Every operator found the next thing: the observe baseline is one slot deep, so a stamp from any move but the last of a batch is unknown; reproduced, held for the next slice. Filed: tree proofs key 63 reads 6 where the task holds 7; ethogram budget note still says elapsed." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR229: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr229.json)) { Write-Error "ADR229: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR229: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr228.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR229 pushed."
