# push-adr169.ps1 -- generated by tools/deliver.py from tools/delivery/adr169.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr169.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr168.ps1"), (Join-Path $root "push-adr168.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- tools/tasks/page-soil-bench-science.json
  if ($st) { Write-Host "adr168 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  tools/tasks/page-tree-visualizer-science.json `
  tools/entry_ledger.json `
  tools/task_ledger.json `
  tools/delivery_ledger.json `
  tools/verify/counts.json `
  tools/harness_board.html `
  tools/published.json `
  tools/delivery/adr169.json `
  docs/ADR-169-the-tree-visualizer-recorded-whole-2026-09-09.md `
  docs/CHANGELOG-2026-09-09-adr169-the-tree-visualizer-recorded-whole.md `
  docs/AI_HARNESS.md `
  tools/push/push-adr169.ps1
git -C $csrbt commit -m "ADR-169: the tree visualizer, recorded whole -- the select-k-th and rank-of queries, the order-statistic tree finally asked" `
  -m "THE TREE VISUALIZER -- tree-visualizer.html, the balanced-BST visualizer that inserts keys into a red-black / AVL / splay / weight-balanced tree and reports node counts, height, rotations and order statistics against an independent Python port of all four strategies -- had its boot tree, morphs and a seeded random build all driven, but TWO OF ITS THREE VALUE-CARRYING INPUTS WERE NEVER DRIVEN: the SELECT-K-TH and RANK-OF boxes, the two order-statistic queries, left at their defaults (1 and 42) and read by nothing. A tree that reports select and rank but is never asked either is a data structure whose two most characteristic queries -- the whole point of an order-statistic tree -- go unexercised. The existing scenario is kept verbatim (the 13-key boot tree at height 4, the 14th key, the ascending 20-key RB build, the four morphs, the seeded random fill), so its assertions hold, and the two inputs are driven at the end on a REBUILT deterministic tree: cleared, then {10, 20, 30} inserted, select(2) is asked and reads 20, rank(30) is asked and reads #3 -- the page's own selectK and rankOf held against the obvious order statistics of three known keys, so both sides of the claim are the same arithmetic and no hand-typed figure can be wrong. tree-visualizer 1 -> 3 OF 3 FIELDS, 80 -> 91 confirmed and 0 refuted, and the kit 518 -> 520 of 521, 26 of 27 pages entered whole. Held: the order-statistic queries do not change the tree, so building a known three-key tree and asking select and rank of it exercises both inputs against answers a reader can check by counting; the rebuild happens after every earlier assertion has been graded. No page was edited -- a task-only slice, the nineteenth page driven end to end, and only cp-characters is left short of whole." `
  -m "Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_01CNn3hvazSDBU2TCgsGXjTt"
git -C $csrbt push
$t = Join-Path $root "_to_delete\adr128.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr129.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr130.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr131.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr132.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr133.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr134.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr135.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr136.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr137.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr138.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr139.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr140.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr141.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr142.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr143.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr144.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr145.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr146.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr147.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr148.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr149.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr150.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr151.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr152.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr153.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr154.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr155.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr156.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr157.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr158.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr159.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr160.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr161.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr162.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr163.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr164.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr165.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr166.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr167.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr168.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr169.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR169 pushed."
