# push-adr238.ps1 -- generated by tools/deliver.py from tools/delivery/adr238.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr238.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr238.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr238 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR238 pushed."; exit 0 }
  Write-Host "adr238 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr237.ps1"), (Join-Path $root "push-adr237.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-237-a-perfect-fit-is-not-an-unstable-one-2026-09-22.md
  if ($st) { Write-Host "adr237 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-238-the-next-bird-says-what-it-will-carry-2026-09-22.md `
  docs/CHANGELOG-2026-09-22-adr238-the-next-bird-says-what-it-will-carry.md `
  docs/AI_HARNESS.md `
  docs/selection-log.html `
  tools/tasks/page-selection-log-science.json `
  tools/task_ledger.json `
  tools/verify/verify_sel.py `
  tools/mutate_sel.py `
  tools/harness_board.py `
  tools/delivery/adr238.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr238.ps1
git -C $csrbt commit -m "ADR-238: the next bird says what it will carry -- the selection log says what the next individual will be logged as, and says so when a tap on a selected dial clears it" `
  -m "The eighth blind trial pressed adult for the third bird while it was still selected; the press cleared the dial and A3 was logged with no age, with nothing on the page saying so. The dials carry forward and a re-press clears, both on purpose; together they were a trap. The page now shows what the next individual will be logged as after every press, says in words when a tap has cleared a dial, and names in the add confirmation what the record is missing. Task 133 to 138 confirmed, verify_sel 83 to 95 held against the record KEEP keeps, new mutate_sel runner." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR238: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr238.json)) { Write-Error "ADR238: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR238: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr237.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR238 pushed."
