# push-adr230.ps1 -- generated by tools/deliver.py from tools/delivery/adr230.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr230.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr230.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr230 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR230 pushed."; exit 0 }
  Write-Host "adr230 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr229.ps1"), (Join-Path $root "push-adr229.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-229-a-stamp-says-which-series-it-is-2026-09-18.md
  if ($st) { Write-Host "adr229 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-230-the-baseline-is-a-ring-not-a-slot-2026-09-18.md `
  docs/CHANGELOG-2026-09-18-adr230-the-baseline-is-a-ring-not-a-slot.md `
  docs/AUTOMATION-HARNESS.md `
  tools/harness_contract.py `
  tools/harness_plugin_page.py `
  tools/verify/verify_contract.py `
  tools/verify/verify_report.py `
  tools/verify/verify_walk.py `
  tools/verify/verify_tasks.py `
  tools/mutate_contract.py `
  tools/mutate_report.py `
  tools/traces/blind8/PROVENANCE.md `
  tools/traces/blind8/OPERATOR.md `
  tools/traces/blind8/page-micro-bench-science.jsonl.gz `
  tools/traces/blind8/page-ordination-science.jsonl.gz `
  tools/traces/blind8/page-field-notebook-science.jsonl.gz `
  tools/traces/blind8/page-selection-log-science.jsonl.gz `
  tools/traces/blind8/tasks/page-micro-bench-science.json `
  tools/traces/blind8/tasks/page-ordination-science.json `
  tools/traces/blind8/tasks/page-field-notebook-science.json `
  tools/traces/blind8/tasks/page-selection-log-science.json `
  tools/delivery/adr230.json `
  docs/AI_HARNESS.md `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr230.ps1
git -C $csrbt commit -m "ADR-230: the baseline is a ring, not a slot (protocol 1.10) -- and the eighth blind trial, four more pages nobody had driven, measures that since= the stamp before a batch is answered" `
  -m "observe since diffed against the last snapshot served and every act served one, so an operator who batched acts and asked for the change since the stamp read before the batch was told unknown, all ten times in the seventh trial. Now a ring of the last 8 stamps per plugin, each diffable; older is unknown and the reason names the depth; a stamp served again moves to newest; the report gets the same ring; the manifest says baselines 8 and that the report stamp is output.stamp. verify_contract 230 to 241, verify_report 249 to 252, mutate_contract 111 to 116, mutate_report 151 to 153. The eighth blind trial -- micro bench, ordination, field notebook, selection log, one attempt each, 35 of 63 outcomes and 116 of 175 claims in 311 calls -- counts non-latest since asks answered unknown at 5 of 32 against the seventh's 10 of 10; verify_tasks 429 to 446 holds both. Found and filed: the snapshot stamp is controls-only and operators read changed false as nothing happened; micro bench drops medium and organism from its zone outputs; selection log dials toggle off on re-press." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR230: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr230.json)) { Write-Error "ADR230: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR230: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr229.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR230 pushed."
