# push-adr215.ps1 -- generated by tools/deliver.py from tools/delivery/adr215.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr215.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr215.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr215 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR215 pushed."; exit 0 }
  Write-Host "adr215 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr214.ps1"), (Join-Path $root "push-adr214.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-214-the-stations-kept-the-run-to-themselves-2026-09-16.md
  if ($st) { Write-Host "adr214 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-215-which-numbers-decide-the-verdict-2026-09-16.md `
  docs/AI_HARNESS.md `
  docs/CHANGELOG-2026-09-16-adr215-which-numbers-decide-the-verdict.md `
  tools/delivery/adr215.json `
  tools/harness_board.html `
  tools/harness_board.py `
  tools/published.json `
  tools/push/push-adr215.ps1 `
  tools/verify/counts.json `
  tools/verify/verify_board.py
git -C $csrbt commit -m "ADR-215: the board printed 'everything is green' beside a reading of 6 / 7, and said nothing about which numbers decide" `
  -m "The Harness Board is this kit's one summary artefact and its headline was not derived from what it displays. all_green was a hand-written conjunction over seven summary fields while the page rendered eleven tiles, six of which do not gate the verdict -- one of them reading '6 / 7 clean under load'. A reader with that and 'Everything the harness knows how to check is green' on one screen has to distrust one of the two, and the page gave them nothing to decide with. FOUND BY A READER, NOT AN AUDIT: a subagent republishing the board noticed the two statements side by side and said so. ADR-141's shape at the top of the kit rather than inside a page: a rule kept in one place and published in another, with nothing holding the two together -- the conjunction could be extended without the page ever mentioning it, and a tile could be added without anyone deciding whether it gates. The verdict is now DERIVED from a named list of seven gates and the list is RENDERED, with any unmet gate marked NOT MET. The honest shape is not 'every tile gates': two of the seven have no tile at all -- the walks and the traces -- so the list is named rather than inferred from what happens to be displayed. Every tile then says which it is: four carry 'counts toward the verdict' and the other seven say in one line what kind of number they are instead, and the renderer ASSERTS it -- a tile that neither gates nor has a reason stops the render rather than printing an unexplained ratio. AND THE RULE FIRES: every check would pass on a page whose banner was hard-coded green, so verify_board breaks a gate on a COPY of the ledgers, re-renders, and requires the banner to go red and that gate -- and only that gate -- to be named NOT MET. verify_board 102 to 112." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_01YPcb1A7CejriRgL9xLrhJ3"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR215: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr215.json)) { Write-Error "ADR215: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR215: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr214.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR215 pushed."
