# push-adr187.ps1 -- generated by tools/deliver.py from tools/delivery/adr187.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr187.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr187.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr187 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR187 pushed."; exit 0 }
  Write-Host "adr187 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr186.ps1"), (Join-Path $root "push-adr186.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- tools/verify/_lab_models.py
  if ($st) { Write-Host "adr186 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  tools/harness_tasks.py `
  tools/verify/verify_tasks.py `
  tools/mutate_tasks.py `
  tools/traces/blind3/PROVENANCE.md `
  tools/traces/blind3/page-breeding-bench-science.jsonl.gz `
  tools/traces/blind3/page-collection-sheet-science.jsonl.gz `
  tools/traces/blind3/page-pheno-tracker-science.jsonl.gz `
  tools/traces/blind3/page-stand-sheet-science.jsonl.gz `
  tools/mutant_ledger.json `
  tools/outputs_ledger.json `
  tools/badinput_ledger.json `
  tools/entry_ledger.json `
  tools/readable_ledger.json `
  tools/delivery_ledger.json `
  tools/verify/counts.json `
  tools/harness_board.html `
  tools/published.json `
  tools/delivery/adr187.json `
  docs/ADR-187-outcomes-not-routes-2026-09-11.md `
  docs/CHANGELOG-2026-09-11-adr187-outcomes-not-routes.md `
  docs/PLAN-operator-api-2026-09-11.md `
  docs/AI_HARNESS.md `
  tools/push/push-adr187.ps1
git -C $csrbt commit -m "ADR-187: outcomes, not routes -- the third blind trial (four operators, four science pages, the goal sentence alone) and a grader that asks what a trace REACHED rather than whether it took the author's route" `
  -m "THE THIRD BLIND TRIAL. Four fresh operators in a stripped checkout, one science page each, the goal sentence verbatim, supervised rungs: all four reached every figure their goal names, in 4-6 attempts and 200-290 calls, and stopped correctly at the DESTRUCTIVE presses. Graded as TRACES all four are UNMET at steps 5, 23, 8 and 16 of scripts 73-165 long -- a task is a script and holding an operator to an author's route measures obedience. grade_outcomes asks the other question: of the readings a task holds the page to, how many did this trace reach, in any order, by any route, with partial credit per claim, writing nothing to the ledger. Floors measured: 30/57, 10/22, 8/12, 5/21 outcomes. The misses are almost all things the TASKS hold that their GOALS never say (a 32 mm rain event, Bear Creek, 'Cap viscid when wet'), so the grade measures that gap too and widening a goal should raise it. verify_tasks 293 -> 308, mutate_tasks 67 -> 73. Six door findings converged across the four operators (silent selector renumbering with stable ids no tool accepts; a page with no controls until observed; pools that undersell; nameless controls; unseparated box text; the page's own rules absent from the door) and are the seven slices of docs/PLAN-operator-api-2026-09-11.md. Two page defects filed, not fixed. No page and no task was edited." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_01YPcb1A7CejriRgL9xLrhJ3"
git -C $csrbt push
$t = Join-Path $root "_to_delete\adr128.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr129.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr130.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr131.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr132.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr133.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr134.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr135.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr136.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr137.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr138.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr139.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr140.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr141.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr142.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr143.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr144.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr145.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr146.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr147.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr148.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr149.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr150.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr151.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr152.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr153.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr154.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr155.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr156.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr157.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr158.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr159.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr160.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr161.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr162.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr163.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr164.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr165.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr166.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr167.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr168.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr169.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr170.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr171.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr172.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr173.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr174.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr175.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr176.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr177.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr178.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr179.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr180.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr181.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr182.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr183.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr184.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr185.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr186.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR187 pushed."
