# push-adr232.ps1 -- generated by tools/deliver.py from tools/delivery/adr232.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr232.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr232.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr232 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR232 pushed."; exit 0 }
  Write-Host "adr232 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr231.ps1"), (Join-Path $root "push-adr231.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-231-if-stamp-guards-either-document-2026-09-18.md
  if ($st) { Write-Host "adr231 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-232-every-science-page-blind-operated-2026-09-20.md `
  docs/CHANGELOG-2026-09-20-adr232-every-science-page-blind-operated.md `
  docs/AUTOMATION-HARNESS.md `
  docs/OPERATOR.md `
  docs/AI_HARNESS.md `
  tools/harness_plugin_page.py `
  tools/mutate_report.py `
  tools/verify/verify_report.py `
  tools/verify/verify_tasks.py `
  tools/tasks/page-ecology-lab-science.json `
  tools/task_ledger.json `
  tools/traces/blind10/PROVENANCE.md `
  tools/traces/blind10/OPERATOR.md `
  tools/traces/blind10/page-ecology-lab-science.jsonl.gz `
  tools/traces/blind10/tasks/page-ecology-lab-science.json `
  tools/delivery/adr232.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr232.ps1
git -C $csrbt commit -m "ADR-232: every science page blind-operated -- the tenth trial drives the ecology lab, the last one, with zero guard refusals -- and read-control on a picker says which row is picked" `
  -m "read-control on a picker listed the rows the filter shows and never said which was picked; now picker.selected names the picked row among the shown ones and picker.selectedNote says why a null is null. The tenth blind trial drives the ecology lab alone -- the kit's longest task, 61 values, nine stations -- through the door that records the guard a call carried: 39 of 55 outcomes, 234 of 263 claims, 132 calls, 19 guards counted from the trace and none refused, against the ninth trial's 127 refusals on one page under the old manual. Every one of the 21 science tasks now has a blind trace. The trial found the goal sentence wrong where the task was right: Bray-Curtis 0.35 and 0.29 and Newick depth 5 and 3 in the prose, 0.31, 0.25, 6 and 4 on the page, in the task and in a Python recomputation; corrected, the task re-run. verify_report 276 to 281, verify_tasks 466 to 479, mutate_report 162 to 165." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR232: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr232.json)) { Write-Error "ADR232: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR232: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr231.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR232 pushed."
