# push-adr231.ps1 -- generated by tools/deliver.py from tools/delivery/adr231.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr231.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr231.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr231 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR231 pushed."; exit 0 }
  Write-Host "adr231 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr230.ps1"), (Join-Path $root "push-adr230.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-230-the-baseline-is-a-ring-not-a-slot-2026-09-18.md
  if ($st) { Write-Host "adr230 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-231-if-stamp-guards-either-document-2026-09-18.md `
  docs/CHANGELOG-2026-09-18-adr231-if-stamp-guards-either-document.md `
  docs/AUTOMATION-HARNESS.md `
  docs/OPERATOR.md `
  tools/harness_contract.py `
  tools/harness_plugin_page.py `
  tools/harness_mcp.py `
  tools/blind_console.py `
  tools/verify/verify_contract.py `
  tools/verify/verify_report.py `
  tools/verify/verify_mcp.py `
  tools/verify/verify_walk.py `
  tools/verify/verify_tasks.py `
  tools/mutate_contract.py `
  tools/mutate_report.py `
  tools/traces/blind9/PROVENANCE.md `
  tools/traces/blind9/OPERATOR.md `
  tools/traces/blind9/page-cell-bench-science.jsonl.gz `
  tools/traces/blind9/page-cp-bench-science.jsonl.gz `
  tools/traces/blind9/page-deployment-log-science.jsonl.gz `
  tools/traces/blind9/page-farm-scout-science.jsonl.gz `
  tools/traces/blind9/tasks/page-cell-bench-science.json `
  tools/traces/blind9/tasks/page-cp-bench-science.json `
  tools/traces/blind9/tasks/page-deployment-log-science.json `
  tools/traces/blind9/tasks/page-farm-scout-science.json `
  tools/delivery/adr231.json `
  docs/AI_HARNESS.md `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr231.ps1
git -C $csrbt commit -m "ADR-231: if_stamp guards either document (protocol 1.11) -- a report stamp guards the figures, the report's stamp ignores the screen chrome, and the ninth blind trial measures both halves" `
  -m "A tally pressed again moves every figure and no control, so a snapshot-stamped guard let the second press through. Now if_stamp takes a report stamp and guards the report: the door asks the target for its report stamp now (Plugin.stamp), refuses stale naming the report and read-report since as the way to see which figures changed; a target with no report and a string that is not a stamp of either series are refused invalid_argument by name; the manifest says which document each kind guards; the MCP trace records the guard a call carried. The ninth blind trial -- cell bench, cp bench, deployment log, farm scout, one attempt each, 71 of 107 outcomes and 184 of 275 claims in 602 calls -- ran in two halves: on the door as first built 10 of 11 report-guard refusals were the screen chrome's clock, so the report now names its chrome and the stamp and diff treat it and the open pane as noise; on the fixed door 0 of 131 were, 99 were figures that had moved and 88 of those with the snapshot stamp unmoved. verify_contract 241 to 261, verify_report 252 to 276, verify_mcp 98 to 101, verify_tasks 446 to 466, mutate_contract 116 to 126, mutate_report 153 to 162. docs/OPERATOR.md is the canonical operator manual with the two faults the trial found in it fixed." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR231: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr231.json)) { Write-Error "ADR231: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR231: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr230.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR231 pushed."
