# push-adr233.ps1 -- generated by tools/deliver.py from tools/delivery/adr233.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr233.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr233.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr233 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR233 pushed."; exit 0 }
  Write-Host "adr233 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr232.ps1"), (Join-Path $root "push-adr232.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-232-every-science-page-blind-operated-2026-09-20.md
  if ($st) { Write-Host "adr232 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-233-the-report-says-what-the-numbers-say-2026-09-21.md `
  docs/CHANGELOG-2026-09-21-adr233-the-report-says-what-the-numbers-say.md `
  docs/AI_HARNESS.md `
  docs/micro-bench.html `
  tools/tasks/page-micro-bench-science.json `
  tools/task_ledger.json `
  tools/verify/verify_mb.py `
  tools/mutate_mb.py `
  tools/harness_board.py `
  tools/delivery/adr233.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/push/push-adr233.ps1
git -C $csrbt commit -m "ADR-233: the report says what the numbers say -- the micro bench's saturation sentence is computed, its breakpoint band is the rule it applies, and organism and medium reach every output" `
  -m "The three micro bench defects the eighth blind trial filed were all live, and the task held all three byte for byte. The growth warning said high points push mu down whatever they did; it now refits without them and says which way they moved mu, with both slopes. The intermediate band printed 13.5 to 16.5 mm for 17/13; it now states the rule and the whole-millimetre range, 14 to 16. Organism and medium were on the form and nothing read them; they are kept per zone and reach the list, the bench sheet and the zone CSV. The task is corrected and re-run. verify_mb 65 to 83 against an independent refit; new runner mutate_mb, 13 of 13 killed." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR233: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr233.json)) { Write-Error "ADR233: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR233: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr232.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR233 pushed."
