# push-adr194.ps1 -- generated by tools/deliver.py from tools/delivery/adr194.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr194.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr194.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr194 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR194 pushed."; exit 0 }
  Write-Host "adr194 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr193.ps1"), (Join-Path $root "push-adr193.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- tools/verify/verify_brief.py
  if ($st) { Write-Host "adr193 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  tools/blind_console.py `
  tools/verify/verify_tasks.py `
  tools/verify/verify_mcp.py `
  tools/mutate_contract.py `
  tools/traces/blind4/PROVENANCE.md `
  tools/traces/blind4/page-stand-sheet-science.jsonl.gz `
  tools/traces/blind4/page-collection-sheet-science.jsonl.gz `
  tools/traces/blind4/page-pheno-tracker-science.jsonl.gz `
  tools/traces/blind4/page-breeding-bench-science.jsonl.gz `
  tools/mutant_ledger.json `
  tools/outputs_ledger.json `
  tools/badinput_ledger.json `
  tools/entry_ledger.json `
  tools/readable_ledger.json `
  tools/verify/counts.json `
  tools/harness_board.html `
  tools/published.json `
  tools/delivery/adr194.json `
  docs/ADR-194-the-fourth-blind-trial-2026-09-12.md `
  docs/CHANGELOG-2026-09-12-adr194-the-fourth-blind-trial.md `
  docs/AI_HARNESS.md `
  tools/push/push-adr194.ps1
git -C $csrbt commit -m "ADR-194: the fourth blind trial -- the same four pages through the door the last five slices built, 53 to 82 outcomes reached and 996 to 398 calls, and the rung the trial harness could not grant" `
  -m "THE LAST OF THE SEVEN SLICES, AND THE ONLY ONE THAT MEASURES THE OTHER SIX. Same four science pages, same goals, same grader, same floors, through the door ADR-188 to ADR-193 built. Outcomes reached 53 -> 82 of 112, claims confirmed 169 -> 213 of 260, calls 996 -> 398, attempts 21 -> 4 (one each, against four to six). Nothing about the grader, the tasks or the pages changed, and not one goal sentence was rewritten. All four operators took the ~100KB snapshot exactly once and worked from the diff -- 'I re-observed zero times after the first call'. THE TRIAL FOUND A DEFECT IN ITSELF: two briefs declare DESTRUCTIVE (ADR-142) and print it (ADR-193), and blind_console hard-coded the supervised three, so two operators were stopped at the goal's last step by the trial harness rather than by the door; --rungs now, default unchanged, and those two scores are lower bounds. Six page defects filed, two found for the second time. The gap two operators reported independently: the diff is control-shaped, and a read-report's figures have no ``since``. verify_tasks 308 -> 331, verify_mcp 89 -> 93, mutate_contract 56 -> 60. Four traces kept in tools/traces/blind4/ with their provenance." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_01YPcb1A7CejriRgL9xLrhJ3"
git -C $csrbt push
$t = Join-Path $root "_to_delete\adr128.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr129.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr130.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr131.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr132.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr133.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr134.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr135.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr136.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr137.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr138.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr139.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr140.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr141.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr142.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr143.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr144.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr145.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr146.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr147.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr148.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr149.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr150.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr151.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr152.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr153.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr154.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr155.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr156.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr157.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr158.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr159.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr160.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr161.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr162.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr163.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr164.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr165.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr166.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr167.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr168.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr169.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr170.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr171.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr172.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr173.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr174.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr175.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr176.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr177.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr178.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr179.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr180.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr181.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr182.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr183.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr184.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr185.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr186.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr187.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr188.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr189.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr190.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr191.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr192.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
$t = Join-Path $root "_to_delete\adr193.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR194 pushed."
