# push-adr240.ps1 -- generated by tools/deliver.py from tools/delivery/adr240.json.
# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what
# the manifest generates, and a hand edit is a failure. Change the manifest.
#
# Run from anywhere:   .\CSRBT\tools\push\push-adr240.ps1
$ErrorActionPreference = "Stop"
$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$root  = (Resolve-Path (Join-Path $csrbt "..")).Path
$lock = Join-Path $csrbt ".git\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }
# THIS SCRIPT PUSHES ONCE (ADR-184). Run a second time, an earlier version of a
# script like this committed the NEXT slice's changes to the paths the two share
# under this slice's message and left that slice's own files behind. The slice is
# committed once its manifest is in HEAD; after that, only an undelivered push is
# this script's to finish.
$mine = git -C $csrbt ls-tree HEAD -- tools/delivery/adr240.json
if ($mine) {
  $ahead = git -C $csrbt rev-list --count "@{u}..HEAD"
  if ([int]$ahead -gt 0) { Write-Host "adr240 is committed but not pushed -- pushing"; git -C $csrbt push; Write-Host "ADR240 pushed."; exit 0 }
  Write-Host "adr240 is already pushed -- nothing to do (modified paths belong to a later slice; run its script)"; exit 0
}
# The slice before this one, wherever its script lives: in the repo from
# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only
# if the file it was supposed to commit is still uncommitted.
$prev = @((Join-Path $PSScriptRoot "push-adr239.ps1"), (Join-Path $root "push-adr239.ps1")) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($prev) {
  $st = git -C $csrbt status --porcelain -- docs/ADR-239-a-name-outlives-the-press-2026-09-22.md
  if ($st) { Write-Host "adr239 is not committed yet -- running its script first"; & $prev }
}
git -C $csrbt add -A `
  docs/ADR-240-a-budget-file-is-the-whole-budget-2026-09-22.md `
  docs/CHANGELOG-2026-09-22-adr240-a-budget-file-is-the-whole-budget.md `
  docs/AI_HARNESS.md `
  docs/ethogram.html `
  tools/tasks/page-ethogram-science.json `
  tools/verify/verify_etho.py `
  tools/mutate_etho.py `
  tools/harness_board.py `
  tools/delivery/adr240.json `
  tools/harness_board.html `
  tools/mutant_ledger.json `
  tools/published.json `
  tools/verify/counts.json `
  tools/delivery_ledger.json `
  tools/task_ledger.json `
  tools/badinput_ledger.json `
  tools/carried_ledger.json `
  tools/destructive_ledger.json `
  tools/entry_ledger.json `
  tools/outputs_ledger.json `
  tools/readable_ledger.json `
  tools/restored_ledger.json `
  tools/takeaway_ledger.json `
  tools/address_ledger.json `
  tools/push/push-adr240.ps1
git -C $csrbt commit -m "ADR-240: a budget file is the whole budget -- the ethogram's note names all three numbers, the sheet says bout of one and names what it excluded, and the budget CSV carries the out-of-sight row and the event rates" `
  -m "The seventh blind trial filed three things on the ethogram and the task certified all three: the budget note called the time in a state 'elapsed' one paragraph under ADR-154's corrected in-no-state note; the budget CSV carried the state rows and nothing else, no out-of-sight row and no event rates; and the sheet said '1 bouts'. The note now names all three numbers (observed, in a state, the session ran), the sheet says bout/bouts and names the excluded and in-no-state time so its lines add up to the clock, and the budget CSV gains an out-of-sight row, one per-observed-minute row per event, and a points-excluded row in point mode. Task 67 to 77 confirmed and refuted on the old page; verify_etho 71 to 86 with a door-driven stepped-clock section stating the durations itself; new mutate_etho 11/11." `
  -m "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_015Ryyc7gWVh4QXAQ9RAFPF1"
if ($LASTEXITCODE -ne 0) { Write-Error "ADR240: git commit failed ($LASTEXITCODE) -- nothing was committed and nothing will be pushed"; exit 1 }
if (-not (git -C $csrbt ls-tree HEAD -- tools/delivery/adr240.json)) { Write-Error "ADR240: the commit ran and this slice's manifest is not in HEAD -- refusing to report a push that did not happen"; exit 1 }
git -C $csrbt push
if ($LASTEXITCODE -ne 0) { Write-Error "ADR240: git push failed ($LASTEXITCODE) -- the commit is local and the remote does not have it"; exit 1 }
$t = Join-Path $root "_to_delete\adr239.tgz"; if (Test-Path $t) { Remove-Item $t -Force }
Write-Host "ADR240 pushed."
