# -*- coding: utf-8 -*-
"""One list, not two: the slice manifest that makes the tarball and the commit.

Every slice of this kit produces two hand-written lists of the same file set --
the tarball's, and the push script's `git add` -- and until this file nothing
compared them. When they disagreed the file reached the disk and never reached a
commit, and EVERY AUDIT IN THE KIT STAYED GREEN, because every audit measures the
working tree and the working tree has the file. That is how four files shipped
by ADR-143 and ADR-144 sat modified and uncommitted for three days: the audits'
own summaries naming a never-exposed control, and verify_organism printing the
lines that differ when two physicals disagree.

So there is one list now. A slice writes `tools/delivery/<id>.json`:

    {"id": "adr147", "chain": "adr146",
     "subject": "one line -- the commit subject",
     "body":    "the paragraph that goes in the commit's second -m",
     "paths":   ["tools/deliver.py", "docs/ADR-147-....md", ...]}

and this file writes BOTH artefacts from it:

    python3 tools/deliver.py --script adr147   # tools/push/push-adr147.ps1
    python3 tools/deliver.py --bundle adr147   # the tarball to hand over
    python3 tools/deliver.py --record adr147   # move the delivery ledger forward
    python3 tools/deliver.py --check           # every manifest, every script

THE PUSH SCRIPT MOVES INTO THE REPO. It is the one artefact of every slice that
lived outside it -- outside every audit, outside every suite, outside the commit
it describes. ADR-096 to ADR-103 kept theirs in `CSRBT/`; from ADR-104 they were
written to the parent directory instead, and the scripts for ADR-104 to ADR-111
no longer exist anywhere, so what those eight slices staged cannot now be read.
Nothing noticed either the drift or the loss, because nothing was looking.

WHAT --check HOLDS

  * every path a manifest names exists;
  * every manifest's generated script is BYTE-IDENTICAL to the one on disk, so
    a hand-edited script is a failure rather than a silent divergence;
  * a manifest's id matches its filename, and its chain names a manifest or an
    older push script that really is there.
"""
import argparse, glob, hashlib, io, json, os, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
MANIFESTS = os.path.join(HERE, "delivery")
PUSH = os.path.join(HERE, "push")
LEDGER = os.path.join(HERE, "delivery_ledger.json")

TRAILER = ('  -m "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>" '
           '-m "Claude-Session: https://claude.ai/code/session_01CNn3hvazSDBU2TCgsGXjTt"')


def sha(path):
    h = hashlib.sha256()
    with io.open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def manifest_path(mid):
    return os.path.join(MANIFESTS, mid + ".json")


def load_manifest(mid):
    p = manifest_path(mid)
    if not os.path.isfile(p):
        raise SystemExit("no manifest %s" % p)
    return json.load(io.open(p, encoding="utf-8"))


def manifests():
    return sorted(os.path.basename(p)[:-5]
                  for p in glob.glob(os.path.join(MANIFESTS, "*.json")))


def ps_quote(s):
    """A PowerShell double-quoted string. Backtick is PowerShell's escape, so it
    has to go first or every later escape is itself escaped."""
    return (s.replace("`", "``").replace('"', '`"')
             .replace("$", "`$").replace("\r", " ").replace("\n", " "))


def script_text(m):
    """The push script for one manifest. Deterministic: same manifest, same
    bytes, which is what lets --check compare instead of trust."""
    mid, paths = m["id"], list(m["paths"])
    # THE SCRIPT COMMITS ITSELF. It is generated, so a manifest that had to
    # remember to list it would be the same two-lists problem one level down --
    # and the record of what a slice staged would be the one file the slice
    # never staged.
    own = "tools/push/push-%s.ps1" % mid
    if own not in paths:
        paths.append(own)
    out = []
    a = out.append
    a("# push-%s.ps1 -- generated by tools/deliver.py from tools/delivery/%s.json." % (mid, mid))
    a("# DO NOT EDIT: `python3 tools/deliver.py --check` compares this file with what")
    a("# the manifest generates, and a hand edit is a failure. Change the manifest.")
    a("#")
    a("# Run from anywhere:   .\\CSRBT\\tools\\push\\push-%s.ps1" % mid)
    a('$ErrorActionPreference = "Stop"')
    a('$csrbt = (Resolve-Path (Join-Path $PSScriptRoot "..\\..")).Path')
    a('$root  = (Resolve-Path (Join-Path $csrbt "..")).Path')
    a('$lock = Join-Path $csrbt ".git\\index.lock"; if (Test-Path $lock) { Remove-Item $lock -Force }')
    if m.get("chain"):
        c = m["chain"]
        a("# The slice before this one, wherever its script lives: in the repo from")
        a("# ADR-147 on, in the parent directory for ADR-112 to ADR-146. It is run only")
        a("# if the file it was supposed to commit is still uncommitted.")
        a('$prev = @((Join-Path $PSScriptRoot "push-%s.ps1"), (Join-Path $root "push-%s.ps1")) |'
          ' Where-Object { Test-Path $_ } | Select-Object -First 1' % (c, c))
        if m.get("chain_probe"):
            a('if ($prev) {')
            a('  $st = git -C $csrbt status --porcelain -- %s' % m["chain_probe"])
            a('  if ($st) { Write-Host "%s is not committed yet -- running its script first"; & $prev }'
              % c)
            a('}')
    a("git -C $csrbt add -A `")
    for i, p in enumerate(paths):
        a("  %s%s" % (p, " `" if i < len(paths) - 1 else ""))
    a('git -C $csrbt commit -m "%s" `' % ps_quote(m["subject"]))
    a('  -m "%s" `' % ps_quote(m["body"]))
    a(TRAILER)
    a("git -C $csrbt push")
    for t in m.get("clean") or []:
        a('$t = Join-Path $root "_to_delete\\%s.tgz"; if (Test-Path $t) { Remove-Item $t -Force }' % t)
    a('Write-Host "%s pushed."' % mid.upper())
    return "\n".join(out) + "\n"


def write_script(mid):
    m = load_manifest(mid)
    if not os.path.isdir(PUSH):
        os.makedirs(PUSH)
    p = os.path.join(PUSH, "push-%s.ps1" % mid)
    io.open(p, "w", encoding="utf-8", newline="\r\n").write(script_text(m))
    return p


def bundle(mid, out=None):
    m = load_manifest(mid)
    paths = list(m["paths"])
    script = os.path.relpath(os.path.join(PUSH, "push-%s.ps1" % mid), ROOT).replace(os.sep, "/")
    if script not in paths:
        paths.append(script)
    out = out or os.path.join("/tmp", "%s.tgz" % mid)
    parent = os.path.dirname(ROOT)
    base = os.path.basename(ROOT)
    args = ["tar", "czf", out, "-C", parent] + ["%s/%s" % (base, p) for p in paths]
    subprocess.run(args, check=True)
    return out, paths


def load_ledger():
    if os.path.isfile(LEDGER):
        try:
            return json.load(io.open(LEDGER, encoding="utf-8"))
        except ValueError:
            pass
    return {"_comment": "Written by tools/deliver.py. Per path: the sha256 of the bytes a slice "
                        "last DELIVERED, and which slice delivered them. audit_delivery names "
                        "anything on disk whose bytes are not in here and that no manifest "
                        "claims -- a file that is on disk and in no commit (ADR-147).",
            "paths": {}}


def save_ledger(state):
    io.open(LEDGER, "w", encoding="utf-8").write(
        json.dumps(state, indent=1, sort_keys=True, ensure_ascii=False) + "\n")


def record(mid, adopt=None):
    """Move the ledger forward for one slice's paths (or adopt a whole tree)."""
    state = load_ledger()
    paths = state.setdefault("paths", {})
    todo = adopt if adopt is not None else load_manifest(mid)["paths"]
    n = 0
    for rel in todo:
        full = os.path.join(ROOT, rel)
        if not os.path.isfile(full):
            continue
        paths[rel] = {"sha": sha(full), "by": mid, "at": int(time.time())}
        n += 1
    save_ledger(state)
    return n


def check():
    """-> [problem strings]. Empty is the pass."""
    bad = []
    for mid in manifests():
        m = load_manifest(mid)
        if m.get("id") != mid:
            bad.append("%s: the manifest's id is %r, not its filename" % (mid, m.get("id")))
        for key in ("subject", "body", "paths"):
            if not m.get(key):
                bad.append("%s: no %s" % (mid, key))
        for p in m.get("paths") or []:
            if not os.path.isfile(os.path.join(ROOT, p)):
                bad.append("%s: names %s, which is not there -- the commit would stage nothing "
                           "for it" % (mid, p))
        c = m.get("chain")
        if c and not (os.path.isfile(manifest_path(c))
                      or os.path.isfile(os.path.join(PUSH, "push-%s.ps1" % c))
                      or os.path.isfile(os.path.join(ROOT, "push-%s.ps1" % c))
                      or os.path.isfile(os.path.join(os.path.dirname(ROOT), "push-%s.ps1" % c))):
            bad.append("%s: chains from %s, and no manifest or script by that name is anywhere"
                       % (mid, c))
        sp = os.path.join(PUSH, "push-%s.ps1" % mid)
        if not os.path.isfile(sp):
            bad.append("%s: no generated script -- run --script %s" % (mid, mid))
        else:
            on_disk = io.open(sp, encoding="utf-8", newline="").read().replace("\r\n", "\n")
            if on_disk != script_text(m):
                bad.append("%s: push-%s.ps1 is not what the manifest generates -- it was edited "
                           "by hand, and the two lists have started to disagree again" % (mid, mid))
    return bad


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--script", metavar="ID", help="write tools/push/push-<ID>.ps1")
    ap.add_argument("--bundle", metavar="ID", help="write the tarball for <ID>")
    ap.add_argument("--out", help="where the tarball goes")
    ap.add_argument("--record", metavar="ID", help="move the delivery ledger forward for <ID>")
    ap.add_argument("--adopt", metavar="ID",
                    help="record every tracked file as delivered by <ID>. For seeding the ledger "
                         "once, from a tree that is known to be committed -- an adoption, not "
                         "evidence, and it says so in the ledger")
    ap.add_argument("--check", action="store_true", help="hold every manifest and every script")
    ap.add_argument("--list", action="store_true", help="the manifests, and what each ships")
    a = ap.parse_args(argv)

    if a.list:
        for mid in manifests():
            m = load_manifest(mid)
            print("%-10s %3d path(s)   %s" % (mid, len(m["paths"]), m["subject"][:70]))
        return 0
    if a.script:
        print("wrote %s" % write_script(a.script))
        return 0
    if a.bundle:
        out, paths = bundle(a.bundle, a.out)
        print("wrote %s -- %d path(s)" % (out, len(paths)))
        return 0
    if a.adopt:
        import audit_delivery as AD
        # NOT the paths a manifest already claims: those are this slice's own
        # work in flight, and adopting them would record as delivered exactly
        # the files that have not been.
        cl = AD.claimed()
        n = record(a.adopt, adopt=[p for p in AD.tracked() if p not in cl])
        state = load_ledger()
        state["_adopted"] = {"by": a.adopt, "at": int(time.time()), "paths": n,
                             "why": "seeded from a tree known to be committed. An adoption is "
                                    "not evidence that these bytes were pushed -- it is the "
                                    "baseline the ratchet starts from."}
        save_ledger(state)
        print("adopted %d path(s) as delivered by %s" % (n, a.adopt))
        return 0
    if a.record:
        print("recorded %d path(s) as delivered by %s" % (record(a.record), a.record))
        return 0
    if a.check:
        bad = check()
        for b in bad:
            print("  ", b)
        print("%d manifest(s), %d problem(s)" % (len(manifests()), len(bad)))
        return 1 if bad else 0
    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
